server:
  port: 8080
spring:
  application:
    name: student
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/student
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

